### ISSUE TITLE
Please switch versioning to 0.x.x rather than 0.0.x

### ISSUE THREAD

**Issue by billinghamj** [gosquared/gosquared-ios#11]
Following semantic versioning rules, using 0.0.x versions does not allow you to release changes which are considered non-breaking. As you can only bump the most significant number, every version bump (as per semver) is considered to be a breaking change.

If you switch 0.x.x style versioning, you can indicate a breaking change by bumping the second number (minor), or a non-breaking change by bumping the third (patch), while still indicating that the pod is in beta.

Then I can require your pod this way, ensuring we can receive bug fixes without the risk of receiving a breaking change:

```ruby
pod 'GoSquared/Autoload', '~> 0.1.0'
```

**Comment by edwellbrook** [comment]
Hey James. I'll definitely be more cautious with versioning. Looking through our changelog I can see a few cases where a minor version bump would have been a better decision.

Thanks for bringing this to my attention and I'll make sure future releases follow semver more closely.

**Comment by billinghamj** [comment]
Probably just means it'd be good to move to 0.1.0 reasonably soon, so you have greater flexibility.

There hasn't been any violation of the spec - it's just that you ignore the left-zeros for the purposes of determining backwards compatibility.
