### ISSUE TITLE
Calling tracking functions from a background thread seems to cause issues

### ISSUE THREAD

**Issue by benthewhite** [gosquared/gosquared-ios#20]
When trying to call tracking from a background thread pinging doesn't work so the main thread needs to be called

```
dispatch_async(dispatch_get_main_queue(), ^{
    [[GoSquared sharedTracker] identify:userID properties:nil];
});
```

**Comment by edwellbrook** [comment]
This was only the pinging that wasn't working, right? Example code is for identify method, so wondering if theres an issue with that as well?

**Comment by benthewhite** [comment]
Not sure. I think we just wrapped everything to be safe

**Comment by edwellbrook** [comment]
If we find other cases where it breaks, let me know and we can reopen, but should work all fine now 😄
