### ISSUE TITLE
On reconnection identify should be called with last good props

### ISSUE THREAD

**Issue by Too-Funky** [gosquared/gosquared-ios#28]
On initial login to an app, 'identify' is called with the user's properties. These properties are used to 'tag' the user in the Visitor widget. A user will be treated as 'tagged' if either the `name` or `email` property is being set.

The tagged properties are cached by the Visitor widget for the duration of their session and are associated with their `visitor_id`. This means that pageview calls made during the session will be attributed to the tagged visitor.

The expected behaviour is that all sessions from a previously identified visitor should be treated as 'tagged' sessions in the Visitor widget.

However, when their initial session ends or is timed out. This Visitor widget no longer has their properties cached and is no longer able to associate a `visitor_id` with their properties. Therefore future sessions from that user show up in the Visitor widget as an anonymous 'Returning' visitor.

Pageviews are correctly tracked in GoSquared People, it is just the Visitor widget that is affected by this caching.

If future sessions could also call 'identify' with any known properties (preferably `name` or `email`) then the Visitor widget would show future sessions as a 'tagged' visitor instead of a `returning` anon visitor.

**Comment by RajChanchal** [comment]
I am facing the same issue. Visitor widget doesn't seem to cache the person_id for future sessions. And even the details of a person (name,  phone etc) in People tables goes missing too in future sessions.

**Comment by edwellbrook** [comment]
@RajChanchal Please update the SDK to the latest version (`v0.6.0`), and use the new `identifyWithProperties:` method. If you need any help getting identify working, please refer to the docs: https://github.com/gosquared/gosquared-ios/blob/master/README.md#people

Thanks.

**Comment by RajChanchal** [comment]
I have updated the SDK to the latest one and have used the `identifyWithProperties:` method. The visitors widget seems to be working fine now. But the 'people' section has still missing name, email and phone. It doesn't seems to update table with `identifyWithProperties:` method.

**Comment by edwellbrook** [comment]
That sounds like a separate issue to this one.

So I can keep track of what needs fixing, could you please open a new issue, or email me (<ed@gosquared.com>).

Please provide as much information and code as you can:
 - your example code
 - enable debug logging (set `[GoSquared sharedTracker].logLevel = GSLogLevelDebug;`)
 - copy and paste what is logged for your identify call. it should look something like this:

```
GSRequest::sending request - GSRequest: 0x7c741a30
Method: POST
URL: https://api.gosquared.com/tracking/v1/identify?site_token=_&api_key=_
Body: {
    "person_id" = 2388975;
    properties =     {
        email = "email@example.com";
        id = 2388975;
        name = "Example User";
    };
    "visitor_id" = "A67EDE50-EAF7-49B7-A795-3BAAC788D29F";
}
```

> **Important:** When copying/pasting your log, remember to remove your `site_token` and `api_key` from the URL
