### ISSUE TITLE
Can not configure GoSquard Chat

### ISSUE THREAD

**Issue by RajChanchal** [gosquared/gosquared-ios#33]
To enable chat feature, I need to have a secret token. But I cannot find it in my project's dashboard.
The code write it as:

```
// this is required for Chat and can be generated from:
// https://www.gosquared.com/setup/general
[GoSquared sharedTracker].secret = @"your-secure-secret";

```
But where can I find this secret? I found no documentation giving me a right direction!! As shown in comments I went [here](https://www.gosquared.com/setup/general) but found nothing.

**Comment by ServicePal** [comment]
Raj,
you need to look under Secure Mode on Settings -> General.
With Secure mode turn on, you should see

The Secure Mode Secret for this project:
xxxxxxxxxxxxxxxxxxxxxxxxxxx

More about Secure Mode
https://www.gosquared.com/docs/api/javascript-tracking-code/secure-mode/
