### ISSUE TITLE
GoSquared chat: iPhone X UI bug

### ISSUE THREAD

**Issue by richardtop** [gosquared/gosquared-ios#38]
![simulator screen shot - iphone x - 2018-01-30 at 05 43 06](https://user-images.githubusercontent.com/8013017/35547689-312bd772-0583-11e8-82bf-731578768fb9.png)

This bug is reproducible in demo project. Chat textfield is placed too low and interferes with home indicator.

**Comment by ServicePal** [comment]
Not just visually annoying, but once you type the 3rd character, the text goes  out of view. Perhaps related to #37.

<img width="403" alt="screen shot 2018-03-28 at 9 10 32 am" src="https://user-images.githubusercontent.com/8471863/38042035-1b0f060a-3268-11e8-85f3-bd5d1c0f0fa7.png">

**Comment by TheDeveloper** [comment]
Hi, thank you for your report.

We are moving issues to a new issue tracker. If you would like to report a new issue or discuss an existing issue further, please get in touch at https://www.gosquared.com/contact/
