### ISSUE TITLE
Text input area is unresponsive on latest version of iOS

### ISSUE THREAD

**Issue by Too-Funky** [gosquared/gosquared-ios#39]
We're aware there is an issue affecting the SDK on the latest version of iOS and are currently investigating.

Tapping does not open the keyboard.
Long pressing does not allow pasting.
Camera roll does not open when tapping camera.

![image](https://user-images.githubusercontent.com/8916587/36727770-620fe056-1bb6-11e8-8572-113b8fe49425.png)

**Comment by jbt** [comment]
This should now be fixed in version `1.0.2`
