### ISSUE TITLE
Out of office assistant view obscuring chat area

### ISSUE THREAD

**Issue by ServicePal** [gosquared/gosquared-ios#40]
Release 1.0.1
Swift 4.0
iOS 10.0 deployment target
Simulator: iPad Air 2 (iOS 10.0)

class ChatFactory {

  init() {
    GoSquared.sharedTracker().token = "GSN-xxxxx-T"
    GoSquared.sharedTracker().key = "xxxxxx"
    GoSquared.sharedTracker().secret = "xxxx"
  }

  func makeController() -> UIViewController {
    var controller: UIViewController = GoSquared.sharedChatViewController()
    controller = UINavigationController(rootViewController: controller)
    controller.modalPresentationStyle = .formSheet

    return controller
  }
}

Chat window pops asking user to leave email and message, yet user cannot enter that information. It is possible to fire off a chat message, but the chat session is obscured.
<img width="847" alt="screen shot 2018-03-27 at 11 26 08 am" src="https://user-images.githubusercontent.com/8471863/37987216-68d3f4b0-31b2-11e8-9860-2a5ec96d670a.png">
<img width="824" alt="screen shot 2018-03-27 at 11 26 44 am" src="https://user-images.githubusercontent.com/8471863/37987218-68ed433e-31b2-11e8-8e13-c86badba206f.png">

I am running during opening hours, so the Out-of_Office assistant should not be displayed.

**Comment by jbt** [comment]
We just pushed some updates to the server-side code for this which should prevent the out-of-office form being displayed when it shouldn't. The SDK should pick up those changes for any future chats. Feel free to reopen this issue if you still see it misbehaving
