### ISSUE TITLE
Device tracking. Not tracking all platforms

### ISSUE THREAD

**Issue by ServicePal** [gosquared/gosquared-ios#41]
v1.0.2
GoSquared implemented in Universal app.
When launched on iPhone, we see the platform detected in the Devices section. When the app is launched on iPad Pro 12.9", the platform comes up as unknown. It's critical for us to be able to to tell which devices people are contacting us from. Plus, we want to know more that just iPhone vs iPad, but the actual model being used. See attached UIDevice extension

Presumably, you have little interest in maintaining this list, so a suggestion would be let developers overwrite the Platform choice, perhaps in GoSquared.sharedTracker().identify(properties: properties)

I can only imagine what the list would look like for Android support, but even on iOS the list is growing and growing.

[UIDevice Extension.txt](https://github.com/gosquared/gosquared-ios/files/1861735/UIDevice.Extension.txt)
<img width="347" alt="screen shot 2018-03-29 at 12 21 46 pm" src="https://user-images.githubusercontent.com/8471863/38110160-908dceb0-334f-11e8-87c7-e0e1d4d544c5.png">
<img width="348" alt="screen shot 2018-03-29 at 12 22 02 pm" src="https://user-images.githubusercontent.com/8471863/38110161-90be96c6-334f-11e8-9840-12406a4c4796.png">

**Comment by TheDeveloper** [comment]
Hi, thank you for your report.

We are moving issues to a new issue tracker. If you would like to report a new issue or discuss an existing issue further, please get in touch at https://www.gosquared.com/contact/
