### ISSUE TITLE
URLs from titles causing null if doesn't include spaces

### ISSUE THREAD

**Issue by steve228uk** [gosquared/gosquared-ios#7]
Even if #6 gets merged there's an issue where if a title doesn't include a space then a null URL will be created.

![screen shot 2015-12-15 at 20 46 18](https://cloud.githubusercontent.com/assets/1169297/11823721/8514dcdc-a36d-11e5-87f0-3b7a2e7aa879.png)

I believe it is caused by this line which is a deprecated method in any case.

https://github.com/gosquared/gosquared-ios/blob/master/GoSquared/GSTracker.m#L88

Perhaps there's a better way to create the URLs or maybe ignore URLs unless the app was launched with one? After all, the titles are being set to adequately describe the view.

**Comment by edwellbrook** [comment]
Was related to how we handle incoming URLs. Also, paths will now only be set if explicitly set in the `trackScreen:withPath:` method.

**Comment by steve228uk** [comment]
@edwellbrook Awesome :v:
